// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBZNIwjlGrXnwiVoY88WY7kE9_W0FzkI',
    appId: '1:225166745384:web:78abcbb71df6e6fba6fa1d',
    messagingSenderId: '225166745384',
    projectId: 'login-auth-53fe5',
    authDomain: 'login-auth-53fe5.firebaseapp.com',
    storageBucket: 'login-auth-53fe5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIx43EMauJYEvofizrgPDgOoC5h-W5mCM',
    appId: '1:225166745384:android:b876b20b3e5f533fa6fa1d',
    messagingSenderId: '225166745384',
    projectId: 'login-auth-53fe5',
    storageBucket: 'login-auth-53fe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVpztg4ChlAfDjD6v7znETgEp5TiYW3BA',
    appId: '1:225166745384:ios:61b823eaf6a65168a6fa1d',
    messagingSenderId: '225166745384',
    projectId: 'login-auth-53fe5',
    storageBucket: 'login-auth-53fe5.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVpztg4ChlAfDjD6v7znETgEp5TiYW3BA',
    appId: '1:225166745384:ios:61b823eaf6a65168a6fa1d',
    messagingSenderId: '225166745384',
    projectId: 'login-auth-53fe5',
    storageBucket: 'login-auth-53fe5.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgBZNIwjlGrXnwiVoY88WY7kE9_W0FzkI',
    appId: '1:225166745384:web:cc61869a9711aee5a6fa1d',
    messagingSenderId: '225166745384',
    projectId: 'login-auth-53fe5',
    authDomain: 'login-auth-53fe5.firebaseapp.com',
    storageBucket: 'login-auth-53fe5.appspot.com',
  );

}